resource_group_name       = "rg-0906-2"
location                  = "westeurope"
storage_account_name      = "storageaccount09062"
application_insights_name = "func-0906-2"
app_service_plan_name     = "ASP-rg09062-acb7"
function_app_name         = "func-0906-2"